use crate::prompt::generator::{MemorySummary, ContradictionInfo};
use crate::config::ServerEntry;

fn format_memories_as_bullets(memories: &[MemorySummary]) -> String {
    if memories.is_empty() {
        return "No relevant patterns activated.".to_string();
    }
    memories.iter().take(10).map(|m| {
        let strength = if m.activation > 0.8 {
            "HIGH"
        } else if m.activation > 0.5 {
            "MED"
        } else {
            "LOW"
        };
        format!("- [{}|{}] {}", m.category, strength, m.content.trim())
    }).collect::<Vec<_>>().join("\n")
}

fn format_contradictions(contradictions: &[ContradictionInfo]) -> String {
    if contradictions.is_empty() {
        return String::new();
    }
    let mut out = String::from("\n## Resolved Contradictions (brain settled these conflicts)\n");
    for c in contradictions.iter().take(5) {
        out.push_str(&format!(
            "- **Current truth:** {}\n  ~~Superseded:~~ {}\n  Reason: {}\n",
            c.winner_content.trim(),
            c.loser_content.trim(),
            c.reason,
        ));
    }
    out
}

pub fn build_living_prompt(
    task: &str,
    task_memories: &[MemorySummary],
    task_contradictions: &[ContradictionInfo],
    infra_memories: &[MemorySummary],
    failure_memories: &[MemorySummary],
    engram_url: &str,
    servers: &[ServerEntry],
    safety_rules: &[String],
) -> String {
    let task_context = format_memories_as_bullets(task_memories);
    let infra_context = format_memories_as_bullets(infra_memories);
    let failure_context = format_memories_as_bullets(failure_memories);
    let contradiction_section = format_contradictions(task_contradictions);

    let server_table = if servers.is_empty() {
        "No server reference configured.".to_string()
    } else {
        let mut table = "| Server | Role | SSH User | Notes |\n|--------|------|----------|-------|\n".to_string();
        for s in servers {
            table.push_str(&format!("| {} | {} | {} | {} |\n", s.name, s.role, s.ssh_user, s.notes));
        }
        table
    };

    let safety_section = if safety_rules.is_empty() {
        String::new()
    } else {
        let rules = safety_rules.iter().map(|r| format!("- {}", r)).collect::<Vec<_>>().join("\n");
        format!("\n## Safety Constraints\n{}\n", rules)
    };

    format!(
        r#"# Eidolon Session Context

You are operating under Eidolon, the Syntheos agent guardian. Eidolon monitors your tool calls via gate hooks and will block unsafe actions.

This context was generated by the Eidolon brain through neural pattern completion, not keyword search. Contradiction resolution has already been applied - what you see below reflects the brain's current understanding.

## Your Task
{task}

## What the Brain Knows About This Task
{task_context}
{contradiction_section}
## Infrastructure Understanding
{infra_context}
{safety_section}
## Server Reference
{server_table}

## Past Failures and Issues Related to This Task
{failure_context}

---

## Syntheos Tools

All services at **{engram_url}**. Use these throughout your session.

| Service | Key Endpoints | When to Use |
|---------|--------------|-------------|
| Engram | POST /search, POST /store, POST /context | Search before guessing. Store after completing work. |
| Chiasm | POST /tasks, PATCH /tasks/:id | Create task on start. Update during. Complete on end. |
| Broca | POST /broca/actions, POST /broca/ask | Log significant actions. Ask infrastructure questions. |
| Axon | POST /axon/publish | Publish events on major milestones. |
| Soma | POST /soma/agents, POST /soma/agents/:id/heartbeat | Register on start. Heartbeat during. |

**MANDATORY:** Search Engram BEFORE asking the user ANY question about servers, credentials, architecture, or past decisions.
"#,
        task = task,
        task_context = task_context,
        contradiction_section = contradiction_section,
        infra_context = infra_context,
        safety_section = safety_section,
        failure_context = failure_context,
        engram_url = engram_url,
        server_table = server_table,
    )
}
